### ISSUE TITLE
Mix Mode Linebreaks

### ISSUE THREAD

**Issue by madwizard78** [yairEO/tagify#518] opened 2020-05-19 01:41 UTC
Is there a way to not allow linebreaks in mix mode?  Realistically I'd like to capture the event and submit a form/click a button but even just stopping the linebreaks from adding another line would be great.  Can probably hack around it but thought I'd check if it's in there somewhere now.

thanks in advance.

**Comment by yairEO** [comment] 2020-05-19 06:40
Duplicate of #517

**Closed by yairEO** 2020-05-19 06:40 UTC
