### ISSUE TITLE
Delimiters spacebar works after next symbol

### ISSUE THREAD

**Issue by MattWhistler** [yairEO/tagify#1106] opened 2022-08-25 08:08 UTC
## Prerequisites

- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/letomedema/edit?html,js,output

### Explanation

- **What is the expected behavior?**
- Should add new tag after spacebar

- **What is happening instead?**
- Instead, after hiting the spacebar it set tag when start writing next tag and then creates two tags, the first one and the first letter from second one

**Comment by yairEO** [comment] 2022-08-25 10:10
Duplicate of https://github.com/yairEO/tagify/issues/1026

**Closed by yairEO** 2022-08-25 10:10 UTC
