### ISSUE TITLE
Under mix mode , when left arrow key is pressed

### ISSUE THREAD

**Issue by muskangupta3** [yairEO/tagify#343] opened 2019-11-18 13:31 UTC
While working under mix mode , while selecting an option in the dropdown menu , if left arrow key is pressed , the whole input string is erased and only the selected value is shown .
I tried this under the demo also , this could be reproduced there as well .

Thanks in advance

**Comment by yairEO** [comment] 2019-11-20 15:56
You probably mean "highlighting" a dropdown option and not "selection" it, because that would simply make a tag out of your text and the whole thing you complain about would be invalid.

Anyway, I just tested this and I cannot reproduce... Maybe it's something specific to your computer, that pressing left-arrow does something in the OS-level?

BUT, I did find another bug while testing this one: If you click the right-arrow while highlighting a suggestion from the dropdown, then it autocomplete it **without** the interpolator character at the start, which then will not allow it to become a tag.

**Comment by muskangupta3** [comment] 2019-11-20 19:01
Hi , yes i meant while highlighting an option from dropdown , and by mistake i mentioned left arrow key , i wanted to tell about right arrow key only

**Comment by yairEO** [comment] 2019-11-20 20:19
Ok so i'm closing this issue because I've opened another one which is cleaer

**Closed by yairEO** 2019-11-20 20:19 UTC
Labels: Cannot Reproduce
