### ISSUE TITLE
Prevent html in mix mode

### ISSUE THREAD

**Issue by gpetrov** [yairEO/tagify#455] opened 2020-04-01 11:11 UTC
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation
When in mix mode the tag uses content editable. However pressing ctrl+b or pasting some html markup corrupt the output. Please prevent those.

**Comment by yairEO** [comment] 2020-04-01 19:41
Duplicate of #376

**Closed by yairEO** 2020-04-01 19:41 UTC
