### ISSUE TITLE
Extra `&#8288;` HTML code in mix mode

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [yairEO/tagify#169] opened 2019-01-01 15:28 UTC
Hello,

I'm behind a strange behaviour with the jQuery file.

After some investigation, I found this part of code in  [dist/jQuery.tagify.min.js](https://github.com/yairEO/tagify/blob/9e2436fc7a3ecf2909bfb2b89f47e23b5926d979/dist/jQuery.tagify.min.js) file

```
        replaceMixStringWithTag: function(t, e, i, n) {
            return i && t && -1 != t.indexOf(e) && (n = this.createTagElem(i), this.value.push(i), t = t.replace(e, n.outerHTML + "&#8288;")), {
                s: t,
                tagElm: n
            }
        }
```

And I can't find why in the mix mode, the originalInput tags are rendered as tags + ``&#8288;``.

I think that ``&#8288;`` is used only in replaceMixStringWithTag() and addMixTag() methods and it's not used in another method. So I don't think that it's usefull somewhere.

The strange thing that I found is when I call loadOriginalValues()

```
        loadOriginalValues: function() {
            var t = this.DOM.originalInput.value;
            if (t) {
                try {
                    t = JSON.parse(t)
                } catch (t) {}
                "mix" == this.settings.mode ? this.parseMixTags(t) : this.addTags(t).forEach(function(t) {
                    t && t.classList.add("tagify--noAnim")
                })
            }
        }
```

Since the mix mode is enabled, the parseMixTags(t) method will be called

```
        parseMixTags: function(n) {
            var s = this;
            return n.split(this.settings.mixTagsAllowedAfter).filter(function(t) {
                return t.match(s.settings.pattern)
            }).forEach(function(t) {
                var e, i = t.replace(s.settings.pattern, "");
                s.isTagWhitelisted(i) && (e = s.normalizeTags.call(s, i)[0], n = s.replaceMixStringWithTag(n, t, e).s)
            }), this.DOM.input.innerHTML = n, this.update(), n
        }
```

In which, if we are using whitelisted tags, each tag text will be normalized in a JSON object and it will be rendered as a HTML tag using replaceMixStringWithTag(n, t, e) method.

Until now everything is OK.

Before continuing, let's take an example:

Input="Hello @homer how are you ?"

The rendered input will be ``Hello [Homer](x)&#8288; how are ?``.

This output will be set in DOM.input.innerHTML

Now the update() method will be called

```
        update: function() {
            this.DOM.originalInput.value = "mix" == this.settings.mode ? this.DOM.input.textContent : JSON.stringify(this.value)
        }
```

Since we are operating in mix mode, DOM.originalInput.value will take the DOM.input.textContent value.

But using the previous example, DOM.input.textContent value is ``Hello Homer&#8288; how are ?``. To be more precise it's value will be seen as "Hello Homer how are ?" but in hexadecimal (for the non visible characeters) it's "Hello Homer%20%60 how are ?"

And that's what's confusing me.

Because in my use-case, I managed to use a custom template

```
        tagTemplate : function(v, tagData){
          return `<tag title='${v}' contenteditable='false' spellcheck='false' value='${v}'>
                    <x title=''></x>
                    <div>
                        <span class='d-none'>@</span>
                        <span class='tagify__tag-text'>${v}</span>
                    </div>
                </tag>`;
        }
```

To keep the pattern character (``@``) in DOM.originalInput. So everytime I render the tags using loadOriginalValues() method, I will never lost my previously rendered tags.

But after seeing this strange behaviour, when loadOriginalValues() method is called the first time it will render the tags normally, but the second time loadOriginalValues() method is called, the previously rendered tags will be deleted and they will never be rendered because of that extra HTML code ``&#8288;``. And this is normal because ``Homer&#8288;`` is not whitelisted.

From Wikipedia:

> ``U+2060 WORD JOINER (HTML &#8288; · WJ): encoded in Unicode since version 3.2. The word-joiner does not produce any space, and prohibits a line break at its position.``

So can I have any answer ?

Thank you

Best regards

**Comment by yairEO** [comment] 2019-01-01 20:40
How are the Tagify textarea gets its value after refresh (second time `loadOriginalValues()` method is called)?

Do you save the value somewhere and then inject it into the form field?

**Comment by mohamedaymenkarmous** [comment] 2019-01-01 23:49
Just to get a simple demo, try setting `&#8288;` code in any place on a HTML page and try reading the HTML value of the HTML code. If my tests are correct, that code will disappear because since the moment when it's set, it will be rendered and it will disappear because it's not visible even in innerHTML.

Steps (in chrome): right-click on a text in a web page -> Inspect -> right-click on a HTML element -> Edit as HTML -> add the `&#8288;` code in a visible text -> exit the Edit mode -> right-click on that element again -> store as global variable -> click on Console tab -> write `temp1.innerHTML` -> Result: that code disappeared.

That's what make me the investigation very harder to understand that I can't see it unless I convert the innerHTML value to hexadecimal.

Best regards

**Comment by yairEO** [comment] 2019-01-02 20:18
But how and where does it get converted to hexadecimal?

**Comment by mohamedaymenkarmous** [comment] 2019-01-02 22:38
I'm not using anything to store the input value after refresh.

Am getting advantage of the update() method when calling loadOriginalValues() method to save the DOM.input.textContent (visible input) in DOM.originalInput.value (textarea). That's why I said it's stored dynamically from input to textarea each time loadOriginalValues() method is called (really it's update() is called).

[update() source code](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L980-L984) :

``
    update(){
        this.DOM.originalInput.value = this.settings.mode == 'mix' ?
            this.DOM.input.textContent :
            JSON.stringify(this.value)
    },
``

I think this is a normal behaviour and I used it as advantage to prepend the hidden pattern `@` in tagTemplate (or using the CSS trick) to render again the previously rendered tags as my personnal custom use-case just to keep rendering the previously rendered tags because the render operation will be applied on DOM.originalInput.value (textarea) [see loadOriginalValues() source code](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L130-L147) (which gets its value previously from input in update() method).

All of this works very well.

The problem is with the [`&#8288;`](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L767) character.

It did not get converted to hexadecimal.

It only get rendered and disappear from the page in ascii format exactly in [this line](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L751).

The problem is that character is appended to the rendered elements each time loadOriginalValues() method is called

if you did a console.log(DOM.input.innerHTML) [after this line](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L751) you will not see it.

But if you define a function that convert a text ascii to hexadecimal you will see that, that character didn't get removed. It belongs appended to the whitelisted characters combined with them as a single word but it stil being invisible in ascii format. That's why the second time loadOriginalValues() method is called, the previously rendered will be unrendered (text stored in textarea which contains whitelisted elements prefixed by the `@` pattern is now appended with a non visible character. It's not visible for a human but it's visible for javascript which knows that character)

Now let me explain how I troubleshooted this issue to see that there is an invisible extra character in hexadecimal.

[After this line](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L751) I defined a function that converts text ascii to hexadecimal string and I applied that function [after this line](https://github.com/yairEO/tagify/blob/610d7a558175c58dd2098232d7da76b2948a9373/src/tagify.js#L751)

```
    parseMixTags( s ){
        function ascii_to_hexa(str){
	  var arr1 = [];
	  for (var n = 0, l = str.length; n < l; n ++) {
		var hex = Number(str.charCodeAt(n)).toString(16);
		arr1.push(hex);
	   }
	  return arr1.join('');
        }
        // example: "@cartman ,@kyle do not    know:#homer".split(/,|\.|\:|\s/).filter(item => item.match(/@|#/) )
        s.split(this.settings.mixTagsAllowedAfter)
            .filter(item => item.match(this.settings.pattern) )
            .forEach(tag => {
                var value = tag.replace(this.settings.pattern, ''),
                    tagData;

                if( this.isTagWhitelisted(value) ){
                    tagData = this.normalizeTags.call(this, value)[0];
                    s = this.replaceMixStringWithTag(s, tag, tagData).s;
                }
            })

        console.log(s); // Before setting the rendered tags in the input: Seeing that the &#8288; character is still there <-----------
        this.DOM.input.innerHTML = s;
        console.log(this.DOM.input.innerHTML); // After setting the rendered tags in the input: Seeing that the &#8288; character is not there anymore <-----------
        console.log(ascii_to_hexa(this.DOM.input.innerHTML));// : Seeing that the &#8288; character is rendered as %20%60 <-------------
        this.update();
        console.log(ascii_to_hexa(this.DOM.originalInput.value));// After update we will see the new textarea value: Seeing that the %20%60 is copied from input to textarea <-------------
        return s;
    },
```

I'm gonna show the result I get if we skip using the tagTemplate or the CSS trick of the prepended pattern (`@`) to make it simple.

Used input (this.DOM.input.innerHTML) before calling loadOriginalValues() method : "Hello \@Homer nice day"

Expected correct result : textarea value should be ``Hello Homer nice day`` input value should be ``Hello [Homer](x) nice day``

Now if we look at the 3 console.log() lines:

First one: `Hello <tag title="Homer" contenteditable="false" spellcheck="false" value="Homer"><x title=""></x><div><span class="tagify__tag-text">Homer</span></div></tag>&#8288; nice day`

As we see before setting the rendered tags in the input (DOM.input.innerHTM), the `&#8288;` character was there.

Second one: `Hello <tag title="Homer" contenteditable="false" spellcheck="false" value="Homer"><x title=""></x><div><span class="tagify__tag-text">Homer</span></div></tag>⁠ nice day`

As we see, after setting the rendered tags in the input (HTML code) the `&#8288;` character is not there anymore.

Third one: `48656c6c6f203c746167207469746c653d22486f6d65722220636f6e74656e746564697461626c653d2266616c736522207370656c6c636865636b3d2266616c7365222076616c75653d22486f6d6572223e3c78207469746c653d22223e3c2f783e3c6469763e3c7370616e20636c6173733d227461676966795f5f7461672d74657874223e486f6d65723c2f7370616e3e3c2f6469763e3c2f7461673e2060206e69636520646179`

This is the hexadecimal value of this.DOM.input.innerHTML in which we haven't found that `&#8288;` character.

But if we convert it again to ascii text using an online converted to be faster [this one for example, otherwise use you prefered hex to ascii converted](https://www.rapidtables.com/convert/number/hex-to-ascii.html), we will find this output `Hello <tag title="Homer" contenteditable="false" spellcheck="false" value="Homer"><x title=""></x><div><span class="tagify__tag-text">Homer</span></div></tag> ` nice day`.

And there we found that special character is there " \`". These 2 characters are represented as `20 60` in hexadecimal.

And as expected with wikipedia it comes from the `&#8288;` character which is an unide character U+2060 (from here comes the found characters `20 60`) because we converted a single unicode character (2 bytes) to hexadecimal and there we saw that there is 2 bytes and then we converted them to ascii (2 bytes separetely 20 and 60 will be the 2 characters `space` and backquote

> `U+2060 WORD JOINER (HTML &#8288; · WJ): encoded in Unicode since version 3.2. The word-joiner does not produce any space, and prohibits a line break at its position.`

Forth one: `48656c6c6f20486f6d65722060206e69636520646179` which belongs to 'Hello Homer \` nice day'. The same as the third explication.

So this character is a 2 byte unicode character which is not visible for us in normal encoding. In the third console.log() we saw that it's not part of the word Homer but as I said it's a unicode character so don't see it as a space + a backquote. There is no space there really. And that's why when a such character is combined with a whitelisted element it will be a non whitelisted character.

This character is used only in addMixTag() and parseMixTags() methods and I don't know it's use.

But if it have no reason to belong I suggest to delete it or to replace it with another character (space for example or another character if you insist to add an ending character).

Thank you for reading all this issue PoC.

Best regards

**Comment by yairEO** [comment] 2019-01-19 14:15
The use for this very specific character is to trick the browser's _caret_ position to stay where it was after a text was converted into a tag and not "jump" back to the beginning. You can simply remove this character from the source code and observe the _caret_ bug. 

What do I need to do to reproduce your problem?
I don't see any problem with the demo pages so it must be something extra that you're doing

**Comment by yairEO** [comment] 2019-02-03 12:58
I will investigate..

**Comment by Fanfoi125** [comment] 2019-09-16 22:07
Hi, same here, but with char \u2060 after the tag. Using the jQuery plugin on Chrome. 
The char is visible from the database (here in a JSON string):
{"link":"[[{\"field\":\"url\",\"value\":\"L'URL de suivi\",\"title\":\"L'URL de suivi\"}]]**\u2060**"}

If I remove this char from the db, tagify will throw an error when reopening:
jQuery.tagify.min.js:7 Uncaught TypeError: t.split is not a function
    at s.parseMixTags (jQuery.tagify.min.js:7)
    at s.loadOriginalValues (jQuery.tagify.min.js:7)
    at new s (jQuery.tagify.min.js:7)

I tried jnpatrick99 workaround, it did not work. The char is still there.

In my use-case, the URL is replaced with a link to a push notification. When clicking on the notification, the URL can not be found by the browser, as there is this char at the end of it (invisible).

Any idea? Thanks

**Comment by yairEO** [comment] 2019-09-17 12:53
@Fanfoi125 - what is this `{"link":"...}` ? how do you make it? can you create a minimal demo for me? you can [fork this jsbin
](https://jsbin.com/degobup/6/edit?html,js,output)

**Comment by Fanfoi125** [comment] 2019-09-17 16:36
@yairEO https://jsbin.com/wunuporoqo/1/edit?html,js,console,output
Using jQuery.

Note that I'm using objects for keywords.
Press #, select let's say "Le titre du suivi", and click submit.
In the console you'll have the field value. If you copy/past this value in notepad (I'm on Windows), you'll notice that at the end of the string - even if you don't see it - you'll have to press the "next" key two times instead of one. The famous char is there. On notepad++, this char makes the software to render stranger things.

If you delete the keyword in the input, then enter it again and submit, you'll see that the chars count next to the button will increase by 1 each time you do that. The invisible chars add up.

Note that this behavior seems to happen only when using objects keywords.

On the server side with PHP,  adding the option JSON_UNESCAPED_UNICODE to json_encode allows to keep those chars hidden (which does not break tagify), but they will break an URL for instance.

I hope it's clearer.

**Comment by yairEO** [comment] 2019-09-17 16:43
Why are you using both `<input>` and `<textarea>` together?

mix-mode `Tagify` should be a `textarea`, not an input element

**Comment by yairEO** [comment] 2019-09-17 16:56
Here's a modified version without Tagify-jQuery (I am against using it, because the non-jQuery version is easier to work with, in my opinion)

https://jsbin.com/hepohal/2/edit?html,js,output

**Comment by yairEO** [comment] 2019-10-16 19:23
Fixed in latest version. No more `&#8288;`

**Closed by yairEO** 2019-10-16 19:23 UTC

**Comment by Fanfoi125** [comment] 2019-10-18 11:54
Hi, thank you for getting back on this issue.
When saving the tags the character is not present anymore, that's great.
However when reopening the tags input, the following error is thrown (same one as displayed on my previous comment):

jQuery.tagify.min.js:7 Uncaught TypeError: t.split is not a function
    at s.parseMixTags (jQuery.tagify.min.js:7)
    at s.loadOriginalValues (jQuery.tagify.min.js:7)
    at new s (jQuery.tagify.min.js:7)
    at HTMLTextAreaElement.<anonymous> (jQuery.tagify.min.js:7)
    at Function.each (jquery.min.js:4)
    at e.fn.init.each (jquery.min.js:4)
    at e.fn.init.r.fn.tagify (jQuery.tagify.min.js:7)
    at HTMLTextAreaElement.<anonymous> (scripts.js:1725)
    at Function.each (jquery.min.js:4)
    at e.fn.init.each (jquery.min.js:4)
    at HTMLDocument.<anonymous> (scripts.js:1717)
    at l (jquery.min.js:4)
    at Object.add [as done] (jquery.min.js:4)
    at e.fn.init.ready (jquery.min.js:4)
    at Object.success (scripts.js:146)
    at l (jquery.min.js:4)
    at Object.fireWith [as resolveWith] (jquery.min.js:4)
    at k (jquery.min.js:6)
    at XMLHttpRequest.<anonymous> (jquery.min.js:6)

**Comment by yairEO** [comment] 2019-10-18 18:48
@Fanfoi125 - cannot reproduce: https://jsbin.com/wupuruk/edit?html,js,output
