### ISSUE TITLE
The background makes a hole when the tag has more than one line

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#999] opened 2022-03-06 12:09 UTC
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://yaireo.github.io/tagify/

add a very long text in the textbox (with spaces) to create a two lines tag.
e.g. add the following text in a tag:
`dsfgdsfgdf gdsfg dsfg ds fg dfg dsfg dsf dsf gdsg dsf gdsf gdsf gdf df gds fgd gds  gdfgdsfgdsf dg dfsg dsfg ds`

### Explanation
The background makes a hole when the tag has more than one line

![image](https://user-images.githubusercontent.com/7249160/156922367-8a87043c-7c9f-42c4-b215-149a3c8022d9.png)

![image](https://user-images.githubusercontent.com/7249160/156922381-dd167269-1b65-48b6-a55f-e2c203a09a0e.png)

After some tests, when you change the shadow width to 1.5em you get a solid background.
```
.tagify__tag__removeBtn:hover + div::before{
  box-shadow: 0 0 0 1.5em var(--tag-remove-bg,rgba(211,148,148,.3)) inset !important;
}
```

**Comment by yairEO** [comment] 2022-03-06 18:58
Duplicate of #755

**Closed by yairEO** 2022-03-06 18:58 UTC
