### ISSUE TITLE
Text Area doesn't allow input with delimiter set to '.' (period).

### ISSUE THREAD

**Issue by FinnBuick** [yairEO/tagify#611] opened 2020-08-07 04:42 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I want to form tags for whole sentences, therefore I'm trying to set the delimiter to be a period e.g. '.'

    var input = document.querySelector('textarea[name=test]'),
      tagify = new Tagify(input, {
        delimiters: '.',
      });

The issue is that the textarea doesn't let me input any text with the delimiter set to '.'

Example issue: [https://jsbin.com/bomifikoga/1/edit?html,js,output](https://jsbin.com/bomifikoga/1/edit?html,js,output)

**Comment by yairEO** [comment] 2020-08-07 18:57
is `mode` setting set to `mix` ?

**Comment by FinnBuick** [comment] 2020-08-08 00:38
I don't want to mix tags and text though, I want each sentence to become a tag after the user types a period.

**Comment by yairEO** [comment] 2020-08-08 16:08
Duplicate of https://github.com/yairEO/tagify/issues/609

**Closed by yairEO** 2020-08-08 16:08 UTC

**Comment by FinnBuick** [comment] 2020-08-10 00:17
Sorry if I'm missing something but I don't see how this is a duplicate of [#609](https://github.com/yairEO/tagify/issues/609) if I'm not using the mix-mode option. I simply want to create new tags after '.' is entered, no mix mode required.

**Comment by yairEO** [comment] 2020-08-10 13:38
May I ask why are you using a `textarea` element instead of an `input` element?

**Comment by yairEO** [comment] 2020-08-10 13:40
Since `delimiters` setting is `regex`, you should write regex:

   delimiters: '\\.'

**Comment by FinnBuick** [comment] 2020-08-12 08:50
Oh right the extra slash was my issue, that has fixed it now. 

Thanks for the help
