### ISSUE TITLE
Mix mode with enabled:0 shows Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by madwizard78** [yairEO/tagify#512] opened 2020-05-15 22:32 UTC
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/vasakac/edit?html,js,output

### Explanation

- **What is the expected behavior?**
 When clicking the drop down it will insert the tag.  

- **What is happening instead?**
   For the `whitelist_2` list (the ones activated with the #) it errors when you try to click one as it can't access the value.

- **What error message are you getting?**
```
  Uncaught TypeError: Cannot read property 'value' of undefined
    at Tagify.createTagElem (tagify.js:1763)
    at Tagify.addTags (tagify.js:1651)
    at Tagify.selectOption (tagify.js:2342)
    at Tagify.onClick (tagify.js:2249)
```

**Comment by yairEO** [comment] 2020-05-16 11:20
is this a duplicate of #508 ?

**Closed** 2020-05-16 11:24 UTC
