### ISSUE TITLE
Onpaste event duplicate tags

### ISSUE THREAD

**Issue by ranjitnadar** [yairEO/tagify#110] opened 2018-09-26 13:04 UTC
![2irjpp](https://user-images.githubusercontent.com/3095820/46081742-e8e1f380-c1ba-11e8-98ed-690f069833d0.gif)

On copy paste duplicate tag generate.

**Comment by yairEO** [comment] 2018-09-30 07:28
I cannot reproduce this.. what are the steps? which browser?

**Comment by ranjitnadar** [comment] 2018-10-09 08:11
When copy paste this duplicate tag generate as mentioned in git screenshot about, this issue comes in all major browser. Now i am unable to reproduce

**Comment by yairEO** [comment] 2018-10-09 08:17
if you cannot reproduce then I'll close this, since I cannot reproduce it as well

**Closed** 2018-10-09 08:16 UTC
Labels: Clarification required
