### ISSUE TITLE
Tagify callback function closure

### ISSUE THREAD

**Issue by gadij** [yairEO/tagify#1048] opened 2022-06-15 07:23 UTC
## Prerequisites
I am running version 4.12.0
I dont see any mentioning of this

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

this is a sandbox that demonstrate the issue
https://codesandbox.io/s/tagify-closure-problem-pxlrmm

### Explanation

- **What is the expected behavior?**
I expect when I blur the second field after the first field has been filled,
to still see the first field's value

- **What is happening instead?**

every time I am blurring on 1 field the value from the other field is disappearing. 

seems that (after debug) the closure of the callback function is wrong, and not up-to-date

**Comment by yairEO** [comment] 2022-06-17 11:00
Can you simplify the example by removing the need for redux at all, and also removing anything which is not needed?
I need a very simple example to be able to examine the code, because right now, as it is, it seems not to be related to Tagify at all

**Comment by gadij** [comment] 2022-06-19 11:51
most of the react applications are using Redux or any state management, this is a part of the application, in very very minified version. if it is used in with a local state (useState), it works but this is not the robust use case.
i believe that it has to do with the react wrapper of tagify itself, since you are using 'useState' with empty dependency array, so if the reference to the onBlur or any of the other callback functions you are setting 'on' to, has changed the re-assigned wont be called with the new closure, so if the callbacks could be added to the dependency array, this can be solved.

**Comment by yairEO** [comment] 2022-06-21 12:36
I still want a much simplified version - the absolute bare minimum which this problem is reproducible at, in order to assist.

Tagify is my hobby and I have many other open-source projects & a full-time day job + million other hobbies and duties, so please help me help you by making it as easy for me as possible, by simplifying the example

**Comment by yairEO** [comment] 2022-07-20 20:21
Closing as OP did not create a simple example case for me to examine, and I cannot be expected to go over the tons of code in the current example because I am too busy doing a million other things like my 50 other open-source projects or cooking and cleaning

**Closed** 2022-07-20 20:22 UTC
Labels: Clarification required
