### ISSUE TITLE
Incorrect tag background for multiline tags

### ISSUE THREAD

**Issue by vkirienko** [yairEO/tagify#969] opened 2022-01-21 12:39 UTC
Hi,

When tag text gets wrapped into multiple lines tag shows white background in the middle.

![image](https://user-images.githubusercontent.com/12551258/150528529-a544e1a9-9c01-42dd-bba9-e898bd4f5b78.png)

**Comment by yairEO** [comment] 2022-01-21 14:51
it is up to you to adjust this, because this is an extreme scenario which Tagify is not handling out-of-the-box


This issue is a duplicate of https://github.com/yairEO/tagify/issues/755

**Closed by yairEO** 2022-01-21 14:51 UTC
