### ISSUE TITLE
Anyway to make the 'only one suggestion' clickable ?

### ISSUE THREAD

**Issue by jesuismaxime** [yairEO/tagify#101] opened 2018-09-05 03:35 UTC
Could be useful to let user click even if there's a single suggestion instead of typing the reste of the word/tag. Is there any way to do that at this moment ?

**Comment by yairEO** [comment] 2018-09-18 07:43
Just pushed a fix. this is a duplicate of #103

**Closed by yairEO** 2018-09-18 07:43 UTC
