### ISSUE TITLE
Focus issues in firefox

### ISSUE THREAD

**Issue by dumbasPL** [yairEO/tagify#1166] opened 2022-12-28 11:38 UTC
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
Can be done on the unmodified template as well, I've added extra padding and a border to show it better.
https://jsbin.com/ruhotomezi/1/edit?html,js,output

### Steps to reproduce

1. Open the above jsbin in firefox
2. click anywhere in `.tagify` to focus it
3. click again on `.tagify` but not on `.tagify__input` (aka the space between the actual input box and the outer `.tagify`)
4. Observe that `.tagify__input` lost its focus while `.tagify` is still focused
5. click anywhere else on the page to unfocus it
6. Observer that the `.tagify--focus` is still present on the `.tagify` element

### Explanation

- **What is the expected behavior?**
Clicking anywhere on the `.tagify` should focus the input

- **What is happening instead?**
In Firefox, clicking on `.tagify` removes focus from `.tagify__input`, and the `.tagify--focus` class remains in the element even after losing focus.

- **What error message are you getting?**
none

### Notes
On browsers other than firefox clicking on `.tagify` keeps the focus on `.tagify__input`.

This can be especially annoying when `.tagify__input` doesn't take up the whole length of the input.

**Comment by DieterHolvoet** [comment] 2023-02-10 12:37
I'm having a similar issue but it doesn't seem to be fixed in the 4.17.7 release. I'm using the library in combination with the [Drupal module](https://www.drupal.org/project/tagify). Browser is the latest Firefox on macOS. My steps to reproduce:

1. Click in a Tagify field, it focuses and the `tagify--focus` class is added.
2. Click in a Tagify field a second time. It becomes impossible to edit.
3. Click outside the Tagify field. The `tagify--focus` class doesn't disappear and the field is broken (not editable) until I refresh the page.

**Comment by yairEO** [comment] 2023-02-11 20:32
Please create a minimal demo for me to examine

**Comment by DieterHolvoet** [comment] 2023-03-07 23:10
I was able to narrow down and reproduce the issue with [the demo you posted in the issue description](https://jsbin.com/ruhotomezi/1/edit?html,js,output). Turns out the problem is that the second time clicking inside the Tagify field you can only focus it if you click inside `.tagify__input`, not just anywhere in the field. Steps to reproduce:

- Click to the left of the `a` option in the field, but still inside the field border. The field focuses and becomes editable.
- Click another time in the same place. The field focuses again, but it doesn't become editable again. The only way to start adding elements again is to click within the actual text field (`.tagify__input`)

This isn't as big a problem in the jsbin example, but it is in the Drupal module. Over there, there isn't a visual difference between `.tagify__input` and the rest of the field, and I don't think there should be.

**Comment by DieterHolvoet** [comment] 2023-03-20 13:35
Should I create a new issue or can you re-open this one?

**Comment by yairEO** [comment] 2023-04-12 09:34
Sorry, I was on vacation. I've verified the bug exists on Firefox and am looking for ways to fix it.

**Closed** 2023-04-12 15:09 UTC
Labels: Bug
