### ISSUE TITLE
Error on paste text in mix mode

### ISSUE THREAD

**Issue by morganpizzini** [yairEO/tagify#506] opened 2020-05-05 15:44 UTC
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- I can paste text in caret position

- input gets cleared from previous values, then copied text is pasted

**Comment by yairEO** [comment] 2020-05-05 16:32
duplicate of #505

**Closed by yairEO** 2020-05-05 16:32 UTC
