### ISSUE TITLE
Single quote character ' (apostrophe) is converted to &#039;

### ISSUE THREAD

**Issue by thomascenni** [yairEO/tagify#705] opened 2020-11-20 18:55 UTC
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

Using tagify with this settings:

`            var tagify = new Tagify(input, {
                whitelist: [],
                enforceWhitelist: false,
                maxTags: 10,
                delimiters: ',',
            })
`

in a textarea field, loading tags by ajax, every time I select a tag with apostrophe, once added is rendered with the code \&#039;
The ajax list is a valid JSON object with "value" field and rendered correctly:
![Screen Shot 2020-11-20 at 15 51 26](https://user-images.githubusercontent.com/33039107/99838824-7970b000-2b48-11eb-98e8-9e8f1e17a6ec.png)

But when I select the field (the second one in the image), this is the result:
![Screen Shot 2020-11-20 at 15 51 41](https://user-images.githubusercontent.com/33039107/99838839-81c8eb00-2b48-11eb-84e8-1840e45bdad6.png)

Any help is really appreciated.

**Comment by yairEO** [comment] 2020-11-21 09:23
I cannot reproduce the bug and you did not create a test page, so...

**Comment by thomascenni** [comment] 2020-11-21 10:59
Sorry, just created a test page here:
https://codepen.io/thomascampinas/pen/ExyBwmR

**Comment by thomascenni** [comment] 2020-11-21 22:03
> Sorry, just created a test page here:
> https://codepen.io/thomascampinas/pen/ExyBwmR

@yairEO did you have the chance to have a look?

**Comment by yairEO** [comment] 2020-11-22 22:50
@thomascenni - yes, it was fixed on the version which I just deployed, a few minutes ago:

    3.21.5

I didn't tag the fix in the commit because apparently another fix also fixed this one, before I had a chance to get to it, so by the time I did test it locally, the problem did not happen any more.

**Closed by yairEO** 2020-11-22 22:50 UTC
