### ISSUE TITLE
React Template example not working with NPM package

### ISSUE THREAD

**Issue by lohit8846** [yairEO/tagify#1051] opened 2022-06-21 23:23 UTC
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codesandbox.io/s/oempc

Please refer to the file TagifyWithTemplates.jsx 

Comment out the import of custom package on line 2 of TagifyWithTemplates.jsx and comment in the import of the NPM package on line 3. The example found in the documentation does not work when using the NPM package

### Explanation

- **What is the expected behavior?**

TagifyWithTemplates example should load when using NPM package for Tagify

- **What is happening instead?**
@yairEO The page crashes before loading with this error. Cannot read properties of undefined (reading 'settings')
Here is a screenshot for proof since my previous issue about this was closed without resolution

<img width="1345" alt="Screen Shot 2022-06-21 at 4 15 37 PM" src="https://user-images.githubusercontent.com/27837168/174912341-62943101-b9fe-4c6a-bf39-41a96de03b6a.png">

Can you please check the difference between the custom tagify package used in the example and the one in NPM, so you can release a working version? Thanks for your help with this. It will hopefully allow me to use this template feature

**Comment by yairEO** [comment] 2022-06-22 18:44
duplicate of #1050

**Closed by yairEO** 2022-06-22 18:44 UTC

**Comment by lohit8846** [comment] 2022-06-22 19:59
The issue was closed without resolution so I wasn't sure if I needed to create a new one. We can track this in the other issue. Thanks
