### ISSUE TITLE
Problem navigating the dropdown list with the keyboard

### ISSUE THREAD

**Issue by alessio-de-padova** [yairEO/tagify#1198] opened 2023-04-18 13:03 UTC
Hello! I am using  version 4.17.8, my react and react-dom versions are 18 (if that may help)  and I am experiencing issues with react.tagify in my application. 
I have found no one else experiencing this so maybe I am just overlooking something. Could it go in contrast with other libraries?

Below is the code that I copied and pasted from the React demo I found online. Everything works perfectly but I can't in anyway access the dropdown through the keyboard. If I press enter or arrow down/up I can interact only with the textarea itself (for example, enter creates a new line). Overall, when I click the selected tag it works fine. 

I thank you for the attention and for having built such an amazing library. It was what we were been looking for for quite a while :) 

Here is the code! https://pastebin.com/9Cg8cYit

**Comment by yairEO** [comment] 2023-04-23 18:10
Hi, does the [demo](https://codesandbox.io/s/tagify-react-wrapper-oempc) works well for you?

if not, please **clone** it and make your changes and paste the link here.

I can speculate some other code in your app is intervening with the keyboard navigation event. 
If that's the case, you need to manually go over your whole code, eliminating the source of the problem by simplifying the code as much as possible until the problem is resolved and then you will know which piece of code is causing it.

**Comment by alessio-de-padova** [comment] 2023-04-26 07:53
The demo is working for me in each browser I usually use (Chrome, Edge etc.). 
I think it could be a problem due to the presence of other libraries (could be either mui5 or react-hotkeys, we will dig into it).
We will report to you as soon as we have something relevant. 
Thanks for your attention and help!

**Comment by yairEO** [comment] 2023-06-01 08:44
Why do you not open a ticket for `react-hotkeys`? 

I see `react-hotkeys` is a dead-project for years now, so they won't fix anything for sure.
Since Tagify exists for many years and you are the first ever to report this, that I can only
assume very few people are affected by this issue.

I believe there is a bug with `react-hotkeys` and I advise you to use another library. find something that doesn't start with the word *"react"*.. that's for sure :)

There are plenty

**Comment by alessio-de-padova** [comment] 2023-06-05 07:53
I can consider this issue closed since we have changed the hotkeys library and (even though there appeared to be same problem if MixedTags was in autofocus) it works completely fine. 

Thanks for the support <3

**Closed** 2023-06-06 13:50 UTC
