### ISSUE TITLE
Allow the tags to be dragged in mix mode

### ISSUE THREAD

**Issue by gpetrov** [yairEO/tagify#454] opened 2020-04-01 11:09 UTC
It will be really useful to be able to order the tags between the text in mixed mode by dragging.

This way if the user placed the tags incorrectly he can move it to the right place.

Do note that the cursor should move on dragging to indicate the new place.

**Comment by yairEO** [comment] 2020-04-01 19:41
Duplicate of #260

**Closed by yairEO** 2020-04-01 19:41 UTC
