### ISSUE TITLE
Writing #homer in the MIX TEXT & TAGS example does nothing

### ISSUE THREAD

**Issue by AndersBillLinden** [yairEO/tagify#234] opened 2019-05-20 14:38 UTC
In the help page
https://yaireo.github.io/tagify/
I select all text reading
cartman and kyle do not know Homer who is `#1`

and press delete to start over.

After writing `#ho`, millhouse is suggested.
After `#hom`, the suggestions dissapear.

Expected behavior is that Homer will be a suggestion in both cases.

**Comment by yairEO** [comment] 2019-05-21 07:24
weird, I cannot seem to reproduce your scenario.
everything is working as expected for me, I select all, delete, and type slow

#homer

And the suggestions are correct & working as expected

**Comment by AndersBillLinden** [comment] 2019-05-24 19:34
![image](https://user-images.githubusercontent.com/1017466/58352342-8c2ef980-7e6b-11e9-9450-a533c5270cfe.png)
![image](https://user-images.githubusercontent.com/1017466/58352355-95b86180-7e6b-11e9-92f9-054fa5a1262c.png)
![image](https://user-images.githubusercontent.com/1017466/58352370-9f41c980-7e6b-11e9-916b-e415d8c63108.png)
![image](https://user-images.githubusercontent.com/1017466/58352392-aff23f80-7e6b-11e9-9b72-49ab4dc413f3.png)
![image](https://user-images.githubusercontent.com/1017466/58352405-b8e31100-7e6b-11e9-89ec-9ceeea9c4205.png)

**Comment by yairEO** [comment] 2019-05-24 21:38
Very odd... I cannot reproduce. May I ask that you try on another computer?

**Comment by AndersBillLinden** [comment] 2019-05-25 09:59
I at least tried to run it in another browser. When pressing delete in firefox, the contents will not become blank. I had to remove texts and tags one by one. Getting correct suggestions however.

**Comment by AndersBillLinden** [comment] 2019-05-25 10:08
Tried using another windows account. Got both suggestions. Tried again with the first account, disabling all exensions. No cake.

**Comment by yairEO** [comment] 2019-05-25 10:16
maybe it's some cache thing? the first windows account maybe has older version of tagify? who knows... it needs to be debug

**Comment by AndersBillLinden** [comment] 2019-05-25 19:27
I access the same webpage with both accounts. I have no cache using the account where the issue occurs.

**Comment by yairEO** [comment] 2019-05-25 20:26
Well, since the code works for me, and since the code is quite simple and I cannot find a reason for it to not working, and as I am working on Tagify as a hobby, I cannot at this point spare time for investigating this since I'm over my head with other bug fixes and personal life...

**Comment by AndersBillLinden** [comment] 2019-05-25 20:34
I investigate it now, but suddenly it works as intended. Could be a browser bug.

**Comment by AndersBillLinden** [comment] 2019-05-25 20:49
`this.value` does not update correctly when I select all text and press delete.

**Comment by AndersBillLinden** [comment] 2019-05-25 21:03
Trying to fix the problem in https://github.com/yairEO/tagify/pull/241

**Comment by yairEO** [comment] 2019-05-28 19:32
hopefully fixed in #241

**Closed by yairEO** 2019-05-28 19:32 UTC
Labels: bug
